services:
  agent.izdrail.com:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WWWUSER: '${WWWUSER:-1000}'
        WWWGROUP: '${WWWGROUP:-1001}'
    image: izdrail/agent.izdrail.com
    container_name: agent.izdrail.com
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '3000:3000'
      - '3000:3000'
    environment:
      WWWUSER: '${WWWUSER}'
      WWWGROUP: '${WWWGROUP}'
      LARAVEL_SAIL: 1
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - '.:/var/www'
    networks:
      - sail


networks:
  sail:
    driver: bridge
